version: 0.0.{build}
image: Visual Studio 2017
build_script:
- ps: >-
    dotnet restore
    
    dotnet msbuild
test_script:
- ps: >-
    dotnet test tests\Sqrawl.UnitTests\Sqrawl.UnitTests.csproj
    